language: node_js
node_js:
  - v9
  - v8
  - v6
after_script: cat ./coverage/lcov.info | coveralls

notifications:
  email:
    recipients:
      - one@example.com
    on_success: never # default: change
    on_failure: never # default: always
